name: myfirstactions
on: 
  pull_request:                          # [pull_request, push, commit]
    types: opened       #on opening a pull request kicks of github action
jobs:
  startup:
    name: Run start up script
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is a Startup Script"    
  build:
    name: This is my Build Task
    runs-on: ubuntu-latest
    needs: startup   #used to define dependency-this will run only after startup script defined above else both run paralelly 
    steps:
      - run: gh pr comment $PR_URL --body "Pull request recieved , will be reviewed"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_URL: ${{github.event.pull_request.html_url}}

